### PR TITLE
Separate datasets from description for search page tabs

### PR DESCRIPTION
**Pull request by jernestmyers**
Goes with https://github.com/VEuPathDB/WDKClient/pull/287  and https://github.com/VEuPathDB/ApiCommonWebsite/pull/142 in resolving https://github.com/VEuPathDB/WDKClient/issues/278

### CODE REVIEW

**Comment by jernestmyers** [comment]
Further apologies for the space/format changes pushed.

[This is the only line changed](https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/201/files#diff-369c38cb808719b1cf9981d39824c88813f2425f8d85c8f26681f0199871e284L65) in `RadioParams.tsx`. Ignore all other changes.

And [this is the relevant code](https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/201/files#diff-4a9e793c9e2a3ab31353739a4682e334ce75df91f2250fe57bbdd0d81d1d4338L57-L91) in `EbrcDescription.tsx` that creates a `DatasetsComponent` separate of the `DescriptionComponent`.

**Comment by dmfalke** [comment]
FWIW, checking the "Hide whitespace" option in "Files changed" helps reduce the noise:
image

**Review by dmfalke — COMMENTED** [review]
What is the reason for removing the `RadioParamElement` styling rules?

**Comment by jernestmyers** [comment]
> What is the reason for removing the `RadioParamElement` styling rules?
> 
> https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/201/files#diff-44d3b3d221b6b84a1ca45e49f4347698cdbb3d62eb8388dcad839ee3bf6c24e3L2-L7

Good question. The existing styling relatively positions the parameters next to the parameter header with this CSS:
```css
.wdk-QuestionForm {
  &RadioParamElement {
    position: relative;
    left: -1.5em;
    bottom: -2.75em;
  }
```
This causes the radio button to be to the left of the form's container, as shown in this screenshot:

image

Since the tabs have a border around the container, the overflow is noticeable and looks bad. Thus, I removed the `&RadioParamElement` styling from `RadioParams.scss` and [instead applied these style changes](https://github.com/VEuPathDB/WDKClient/pull/287/files#diff-530ae806e28625fdf06df818917163cc6c7c629fcdc694bc593a63fd1a50cae9R45-R54) to the `ParameterHeading` class that lives in WDKClient's `DefaultQuestionForm.scss`.

**Review by dmfalke — APPROVED** [review]

**Pull request merged**
