### PR TITLE
Remove unnecessary permissions checks and upgrade eda packages

### PR DESCRIPTION
**Pull request by asizemore**
This PR relates to
- `web-study-data-access` [PR 8](https://github.com/VEuPathDB/web-study-data-access/pull/8)
- `web-eda` [PR 982](https://github.com/VEuPathDB/web-eda/pull/982)

## Notable changes
1. Removes all instances of `approvedStudies`
2. Removes `skipStudyPermissions` flag and the `getCurrentUser` override
3. upgrade version of `eda` and `study-data-access` (In progress)

## Open questions
1. I also found a few other instances of `user` involved in the files I changed. For example, `connect(state => ({user: state.globalData.user}), { attemptAction })` in `DownloadLink.jsx`. Or `user` is sent to another component in `StudyAnswerController.jsx`. Should these get removed as well? Seems like they could be removed but i don't fully understand these uses so i didn't remove them just yet.

## Testing
Tested clinepi dev (see also ClinEpiWebsite [PR 25](https://github.com/VEuPathDB/ClinEpiWebsite/pull/25))
Tested mbio legacy with linked web-common and no other chnages. No errors.
Tested mbio eda feature site branch with linked web-common and upgraded study-data-access. No errors. Works great!

### CODE REVIEW

**Comment by dmfalke** [comment]
> I also found a few other instances of `user` involved in the files I changed. For example, `connect(state => ({user: state.globalData.user}), { attemptAction })` in `DownloadLink.jsx`. Or `user` is sent to another component in `StudyAnswerController.jsx`. Should these get removed as well? Seems like they could be removed but i don't fully understand these uses so i didn't remove them just yet.

If `user` isn't being used by anything else, then it would be great to remove that. You would change it to something like this:
```
connect(null, { attemptAction })
```

**Review by dmfalke — APPROVED** [review]
I'm going to go ahead an approve this, but I think it would be great to remove the `connect` code acquiring the `user` object, as you referenced above.

**Review by jtlong3rd — APPROVED** [review]
This is great! In addition to simplifying that `connect`, it should also be fine to remove that passing of ["user" in StudyAccessController](https://github.com/VEuPathDB/EbrcWebsiteCommon/blob/bc6e1f46271cfd8be086c7d3fa96123e42c52e0a/Client/src/component-wrappers/StudyAnswerController.jsx#L53) you noticed, because the [component it wraps](https://github.com/VEuPathDB/WDKClient/blob/0314885ad1b0f0c303cde0dbd58d49f0519c7dfd/Client/src/Controllers/AnswerController.tsx) doesn't actually use `user`.

**Comment by asizemore** [comment]
Awesome thank you @jtlong3rd and @dmfalke ! I removed a few extra uses of `user` as you suggested. 

Notably, when the `connect` function lost arguments that included `user`, sometimes they had no arguments left. Based on my tiny understanding of [connect](https://react-redux.js.org/api/connect), seems like there's no reason to connect `null` with the component (?) so i just removed `connect` in these cases. Example in `StudyCard`.

When tested, all seems to be working well, but if you have a moment to give a quick thumbs up or down to removing `connect` in these cases, i'd be very grateful! I'm getting more comfortable with typescript + react, but now adding in redux is getting a little crazy again haha 😄

**Review by jtlong3rd — APPROVED** [review]
All the additional removals of `user` should be fine!

**Comment by dmfalke** [comment]
The only one that gives pause is the StudyAnswerController component
wrapper. Component wrappers can be tricky and it’s not immediately clear if
something else is relying on user being passed to DefaultComponent.

(Typing on my phone, so sorry for brevity)

**Comment by asizemore** [comment]
@dmfalke no worries! Would you prefer i revert that change? Or alternatively we're still a few weeks from release so if you think it'll fail loudly, we can see if anyone catches something during QA?

No preference from me!

**Comment by dmfalke** [comment]
@asizemore go for it. If you want, you can take a quick look at AnswerController in wdk-client and see if it uses the user object, which is doubtful.

**Pull request merged**
